#!/usr/bin/env node
const axios = require('axios');

/** Parses --key=value args. */
function parse(argv) {
  const out = {};
  for (const item of argv) {
    if (!item.startsWith('--')) continue;
    const [k, v] = item.slice(2).split('=');
    out[k] = v ?? 'true';
  }
  return out;
}

/** Creates pull request through GitHub REST or mock path. */
async function main() {
  const args = parse(process.argv.slice(2));
  const owner = process.env.GITHUB_OWNER || args.owner || 'mock-owner';
  const repo = process.env.GITHUB_REPO || args.repo || 'mock-repo';
  const base = args.base || process.env.GITHUB_DEFAULT_BRANCH || 'main';
  const head = args.head || 'feature/ruflo-manual';
  const title = args.title || 'FORGEMIND generated PR';
  const body = args.body || 'Generated by FORGEMIND';

  if (!process.env.GITHUB_TOKEN) {
    console.log(JSON.stringify({ ok: true, mock: true, url: `https://github.com/${owner}/${repo}/pull/1` }, null, 2));
    return;
  }

  const response = await axios.post(
    `https://api.github.com/repos/${owner}/${repo}/pulls`,
    { title, head, base, body },
    {
      headers: {
        Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    },
  );

  console.log(JSON.stringify({ ok: true, number: response.data.number, url: response.data.html_url }, null, 2));
}

main().catch((error) => {
  console.error(`[create-pr] failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
